repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
        args: [--autofix]
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
    -   id: pretty-format-kotlin
        args: [--autofix]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        files: "^(frontend)/.*"
-   repo: https://github.com/daveshanley/vacuum
    rev: v0.8.5
    hooks:
    -   id: vacuum
        files: (^|/)(openapi|swagger).*\.(json|ya?ml)$

exclude: '^(frontend)/(tsconfig.app.json|package.json|tsconfig.json|tsconfig.node.json|package-lock.json|openapitools.json)$'
